version: '3.8'

services:
  app:
    build: .
    image: yasiith/blog-app:latest

  backend:
    build:
      context: ./backend
    image: ${DOCKER_USER:-yasiith}/blogapp:backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: ./next-blog-app
    image: ${DOCKER_USER:-yasiith}/blogapp:frontend
    ports:
      - "3000:3000"
<<<<<<< HEAD
    volumes:
      - ./next-blog-app:/app
    command: ["npm", "run", "dev"]

    
=======
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:5000
>>>>>>> 8eb5308dcc89bb5d7e71712f8880b3231d587f08
    depends_on:
      - backend
    restart: unless-stopped

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
