version: '3.8'

services:
  backend:
    image: ${DOCKER_USER}/blogapp:backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://SahanM:Sahan2001@blogger.3xdjq.mongodb.net/?retryWrites=true&w=majority&appname=blogger
      - CLOUDINARY_CLOUD_NAME=dsecpawul
      - CLOUDINARY_API_KEY=586741624489412
      - CLOUDINARY_API_SECRET=g3afHFKSY5R8dYeRI-UeLCxFNTs
      - JWT_SECRET=da15d3d7717b8f3252275be8bbd0f9854252ce5d20efa758f3c8b7261875c263
    restart: unless-stopped

  frontend:
    image: ${DOCKER_USER}/blogapp:frontend
    ports:
      - "80:3000"
    environment:
      - REACT_APP_API_URL=http://${SERVER_IP}:5000
    restart: unless-stopped