version: '3.8'

services:
  app:
    build: .
    image: yasiith/blog-app:latest

  backend:
    build:
      context: ./backend
    image: ${DOCKER_USER:-yasiith}/blogapp:backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: ./next-blog-app
    image: ${DOCKER_USER:-yasiith}/blogapp:frontend
    ports:
      - "3000:3000"



  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
