
version: '3.8'

services:
  backend:

    build: ./backend
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - database
    command: ["npm", "run", "start"]
    restart: unless-stopped

  frontend:
    build: ./next-blog-app
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./next-blog-app:/app
    command: ["npm", "run", "dev"]
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:5000
    
    depends_on:
      - backend
    restart: unless-stopped

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
