---
- name: Setup and Run Docker Containers
  hosts: all
  become: yes

  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Pull Docker images
      command: docker pull {{ item }}
      with_items:
        - "yasiith/blogapp:frontend" 
        - "yasiith/blogapp:backend" 


    - name: Create Docker network if not exists
      command: docker network ls | grep mynetwork || docker network create mynetwork

    - name: Run backend container
      command: >
        docker run -d --name backend_container --network mynetwork
        -e MONGODB_URI="mongodb+srv://SahanM:Sahan2001@blogger.3xdjq.mongodb.net/?retryWrites=true&w=majority&appname=blogger"
        -p 5000:5000 yasiith/blogapp:backend 

    - name: Run frontend container
      command: >
        docker run -d --name frontend_container --network mynetwork
        -p 80:3000 yasiith/blogapp:frontend